cache:
  go: true
  directories:
  - $HOME/.cache
  - $HOME/bin
  - $HOME/gopath/pkg/mod
language: go
go:
- 1.10.x
- 1.11
- 1.12
- 1.6
- 1.7
- 1.8
- 1.9
- master

matrix:
  include:
  - go: 1.x
    env: task=bench
  - go: 1.x
    install: curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | bash -s -- -b $HOME/bin v1.16.0
    env: task=clean

install: true
script: ./script/${task:-test}
after_success: if [[ -z "$task" ]] ; then bash <(curl -s https://codecov.io/bash) ; fi
